#!/usr/bin/env python3
"""
Upstox OAuth Token Generator
Run this once per day to get a fresh access token.
The token is saved to .dev.vars so the MCP server can use it.

Usage:
  python3 get_token.py
"""

import os
import urllib.parse
import webbrowser
from http.server import BaseHTTPRequestHandler, HTTPServer
import json

try:
    import requests
except ImportError:
    print("Installing requests...")
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "requests"])
    import requests

REDIRECT_URI = "http://127.0.0.1:8000/callback"
CALLBACK_PORT = 8000
DEV_VARS_FILE = os.path.join(os.path.dirname(__file__), ".dev.vars")


def load_credentials():
    """Load API key and secret from .dev.vars or prompt the user."""
    creds = {}
    if os.path.exists(DEV_VARS_FILE):
        with open(DEV_VARS_FILE) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    creds[k.strip()] = v.strip()

    api_key = creds.get("UPSTOX_API_KEY") or input("Enter your Upstox API Key: ").strip()
    api_secret = creds.get("UPSTOX_API_SECRET") or input("Enter your Upstox API Secret: ").strip()
    return api_key, api_secret


def get_auth_code(api_key):
    """Open browser for Upstox OAuth and capture the auth code via local callback."""
    encoded_redirect = urllib.parse.quote(REDIRECT_URI, safe="")
    auth_url = (
        f"https://api.upstox.com/v2/login/authorization/dialog"
        f"?response_type=code&client_id={api_key}&redirect_uri={encoded_redirect}"
    )

    print(f"\nOpening Upstox login in your browser...")
    print(f"If it doesn't open automatically, visit:\n{auth_url}\n")
    webbrowser.open(auth_url)

    captured = {}

    class CallbackHandler(BaseHTTPRequestHandler):
        def do_GET(self):
            parsed = urllib.parse.urlparse(self.path)
            query = urllib.parse.parse_qs(parsed.query)
            captured["code"] = query.get("code", [None])[0]
            captured["error"] = query.get("error", [None])[0]

            self.send_response(200)
            self.send_header("Content-type", "text/html")
            self.end_headers()
            if captured["code"]:
                self.wfile.write(b"<h2>Authorization successful! You can close this tab.</h2>")
            else:
                self.wfile.write(b"<h2>Authorization failed. Check the terminal.</h2>")

        def log_message(self, format, *args):
            pass  # suppress server logs

    print(f"Waiting for Upstox to redirect to {REDIRECT_URI} ...")
    httpd = HTTPServer(("127.0.0.1", CALLBACK_PORT), CallbackHandler)
    httpd.handle_request()

    if captured.get("error"):
        print(f"Auth error: {captured['error']}")
        return None
    return captured.get("code")


def exchange_token(api_key, api_secret, auth_code):
    """Exchange the auth code for an access token."""
    print("Exchanging code for access token...")
    response = requests.post(
        "https://api.upstox.com/v2/login/authorization/token",
        data={
            "code": auth_code,
            "client_id": api_key,
            "client_secret": api_secret,
            "redirect_uri": REDIRECT_URI,
            "grant_type": "authorization_code",
        },
        headers={"accept": "application/json", "Content-Type": "application/x-www-form-urlencoded"},
    )

    if response.status_code != 200:
        print(f"Token exchange failed ({response.status_code}): {response.text}")
        return None

    return response.json().get("access_token")


def save_to_dev_vars(api_key, api_secret, access_token):
    """Write/update .dev.vars with the new token (preserves other vars)."""
    existing = {}
    if os.path.exists(DEV_VARS_FILE):
        with open(DEV_VARS_FILE) as f:
            for line in f:
                line = line.strip()
                if "=" in line and not line.startswith("#"):
                    k, v = line.split("=", 1)
                    existing[k.strip()] = v.strip()

    existing["UPSTOX_API_KEY"] = api_key
    existing["UPSTOX_API_SECRET"] = api_secret
    existing["UPSTOX_ACCESS_TOKEN"] = access_token

    with open(DEV_VARS_FILE, "w") as f:
        f.write("# Upstox MCP Server - local environment variables\n")
        f.write("# This file is auto-generated by get_token.py\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")

    print(f"Token saved to {DEV_VARS_FILE}")


if __name__ == "__main__":
    print("=== Upstox Token Generator ===")
    print("You need an API Key and Secret from https://account.upstox.com/developer/apps\n")

    api_key, api_secret = load_credentials()
    auth_code = get_auth_code(api_key)

    if not auth_code:
        print("Failed to get authorization code. Exiting.")
        exit(1)

    print(f"Got authorization code.")
    access_token = exchange_token(api_key, api_secret, auth_code)

    if not access_token:
        print("Failed to get access token. Exiting.")
        exit(1)

    save_to_dev_vars(api_key, api_secret, access_token)
    print("\nDone! Now start the MCP server with: npm run start")
    print("Then restart Claude Code for the MCP connection to activate.")
