/** OHLCV candle from Upstox historical data */
export interface Candle {
  timestamp: string;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
  oi: number;
}

export type SignalType = "BUY" | "SELL";

/** Trading signal generated by a strategy */
export interface Signal {
  index: number;
  type: SignalType;
  price: number;
  date: string;
  reason: string;
}

/** A completed trade with entry/exit info */
export interface Trade {
  entryDate: string;
  entryPrice: number;
  exitDate: string;
  exitPrice: number;
  quantity: number;
  pnl: number;
  pnlPct: number;
  holdingDays: number;
  exitReason: string;
}

/** Full backtest result */
export interface BacktestResult {
  trades: Trade[];
  metrics: PerformanceMetrics;
  equityCurve: EquityPoint[];
  drawdownSeries: DrawdownPoint[];
}

export interface EquityPoint {
  date: string;
  equity: number;
}

export interface DrawdownPoint {
  date: string;
  drawdown: number;
  drawdownPct: number;
}

/** Performance metrics for a backtest run */
export interface PerformanceMetrics {
  totalTrades: number;
  winningTrades: number;
  losingTrades: number;
  winRate: number;
  totalReturn: number;
  totalReturnPct: number;
  cagr: number;
  sharpeRatio: number;
  maxDrawdown: number;
  maxDrawdownPct: number;
  avgWin: number;
  avgLoss: number;
  profitFactor: number;
  expectancy: number;
}

/** Market regime classification */
export type MarketRegime =
  | "trending_up"
  | "trending_down"
  | "range_bound"
  | "high_volatility";

export type StrategyName =
  | "sma_crossover"
  | "ema_crossover"
  | "supertrend"
  | "vwap_crossover"
  | "rsi_overbought_oversold"
  | "macd_signal_cross"
  | "bollinger_squeeze"
  | "stochastic_crossover"
  | "atr_trailing_stop"
  | "buy_the_dip";

/** Strategy function signature — all strategies are pure functions */
export type StrategyFn<T extends Record<string, number | string>> = (
  candles: Candle[],
  params: T
) => Signal[];

/** Strategy definition with metadata */
export interface StrategyDefinition<
  T extends Record<string, number | string> = Record<string, number | string>,
> {
  name: StrategyName;
  fn: StrategyFn<T>;
  defaults: T;
  description: string;
  regimes: MarketRegime[];
}

// --- Strategy-specific param interfaces ---

export interface SmaCrossoverParams {
  fastPeriod: number;
  slowPeriod: number;
}

export interface EmaCrossoverParams {
  fastPeriod: number;
  slowPeriod: number;
}

export interface SupertrendParams {
  period: number;
  multiplier: number;
}

export interface VwapCrossoverParams {
  anchor: string; // "day" for daily reset
}

export interface RsiParams {
  period: number;
  overbought: number;
  oversold: number;
}

export interface MacdParams {
  fastPeriod: number;
  slowPeriod: number;
  signalPeriod: number;
}

export interface BollingerSqueezeParams {
  period: number;
  stdDev: number;
  squeezeThreshold: number;
}

export interface StochasticCrossoverParams {
  kPeriod: number;
  dPeriod: number;
  overbought: number;
  oversold: number;
}

export interface AtrTrailingStopParams {
  atrPeriod: number;
  multiplier: number;
  adxPeriod: number;
  adxThreshold: number;
}

export interface BuyTheDipParams {
  buyDropPct: number;
  sellTargetPct: number;
  stopLossPct: number;
  maxHoldDays: number;
}

/** MACD indicator result */
export interface MacdResult {
  macdLine: number[];
  signalLine: number[];
  histogram: number[];
}

/** Bollinger Bands result */
export interface BollingerResult {
  upper: number[];
  middle: number[];
  lower: number[];
  width: number[];
}

/** Supertrend result */
export interface SupertrendResult {
  supertrend: number[];
  direction: number[]; // 1 = up (bullish), -1 = down (bearish)
}

/** Stochastic result */
export interface StochasticResult {
  k: number[];
  d: number[];
}

/** ADX result */
export interface AdxResult {
  adx: number[];
  plusDi: number[];
  minusDi: number[];
}

/** Backtest configuration */
export interface BacktestConfig {
  initialCapital: number;
  quantity: number;
  allowAccumulation: boolean;
}

/** Optimization result */
export interface OptimizationResult {
  bestParams: Record<string, number | string>;
  bestMetric: number;
  optimizeFor: string;
  topResults: Array<{
    params: Record<string, number | string>;
    metrics: PerformanceMetrics;
  }>;
  totalCombinations: number;
}

/** Strategy suggestion result */
export interface StrategySuggestion {
  strategy: StrategyName;
  score: number;
  metrics: PerformanceMetrics;
  rank: number;
}

export interface SuggestResult {
  regime: MarketRegime;
  suggestions: StrategySuggestion[];
  recommendedStrategy: StrategyName;
}
